.catalog:
  name: master
  version: v0.0.1
  description: demo-service1
  uuid: master-0

demo-service1-app:
  scale: 1
  health_check:
    port: 80
    interval: 10000
    strategy: none
    unhealthy_threshold: 2
    request_line: GET / HTTP/1.1
    healthy_threshold: 2
    response_timeout: 2000
