.catalog:
  name: develop
  version: ferhimedamine_demo-service1_develop_0.0.1_1_8e4d7d31
  description: demo-service1
  uuid: develop-0

demo-service1-app:
  scale: 1
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 80
    unhealthy_threshold: 2
    interval: 10000
    strategy: none
