demo-service1-app:
  image: ferhimedamine/demo-service1:ferhimedamine_demo-service1_feature-html_0.0.1_3_5f20a931
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    traefik.enable: 'true'
    traefik.alias: service1
    traefik.port: '80'
    traefik.domain: test.cloudbuzz.io
